### PR TITLE
Theme Controller and Logo Art Recreations and Additions

### PR DESCRIPTION
**Pull request by shinzon76**
Added art to support new MAME/MESS systems

This is a WIP and I'll be including other commits. Open to any feedback.

### CODE REVIEW

**Comment by fabricecaruso** [comment]
you deleted supracan.png for superacan.svg 
-> The theme name for this system is supracan, superacan does not exist, so it won't work. https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L2393
Please rename superacan.svg to supracan.svg

**Comment by shinzon76** [comment]
> you deleted supracan.png for superacan.svg -> The theme name for this system is supracan, superacan does not exist, so it won't work. https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_systems.yml#L2393 Please rename superacan.svg to supracan.svg

Fixed.

**Comment by fabricecaruso** [comment]
I'm you were already doing it while I was writing ;-)

**Comment by shinzon76** [comment]
This is ready for review

**Comment by fabricecaruso** [comment]
It's fine to me, but...
In the "consoles" I usually add a shadow & there's no shadow in the images you added/changed.
Is is possible you add shadows like for the other systems ?

**Comment by shinzon76** [comment]
> It's fine to me, but... In the "consoles" I usually add a shadow & there's no shadow in the images you added/changed. Is is possible you add shadows like for the other systems ?

Sure, not a problem. ill update do another commit with dropshadows for consoles soon.

**Comment by shinzon76** [comment]
I decided to do controllers too. I'll do another commit soon with the requested drop shadows on consoles and I'll be finished

**Comment by fabricecaruso** [comment]
tell me when it's finished ;-)

**Pull request merged**
